//=======================================================
//  This code is generated by HX1006A Project Builder
//=======================================================

module mcnt_test(

////////////CLOCK//////////
input 		          		CLK_50,

////////////SEG8//////////
output 		   [7:0]       SEL,
output 		   [7:0]     	DIG,

////////////SW//////////
input 		     [3:0]		SW,

////////////KEY//////////
input 		     [1:0]		KEY,

////////////BEEP//////////
output 		          		BEEP 

);

/*_______________________________*/

wire clk_disp;		//Segment Selection Switching Clock
wire en,reset_n;	//Enable, Reset
wire [31:0] q;		//wire q
wire [31:0] m;		//wire m

assign clk_disp = q[15];				 //Set segment Selection Switching Clock
assign {en, reset_n} = KEY;			 //Set Enable and Reset	
assign m = {4'd0, SW, 1'b1, 23'd0};  //Controlling Counter Module with SW Input Signal


/*Instantiation module*/
mcnt u_mcnt(
	.clk			(CLK_50),
	.rst_n		(reset_n),
	.en			(en),
	.m				(m),
	.q				(q),
	.fout			(BEEP)
);

seg_disp u_seg_disp
(
	.clk			(clk_disp),
	.rst_n		(reset_n),
	.Q1			(q),
	.SEL			(SEL),
	.DIG			(DIG)
);
/*_______________________________*/

endmodule
